### ISSUE TITLE
Embed the `client index` to `connection payload packet` and `connection disconnect packet`

### ISSUE THREAD

**Issue by kienhg96** [mas-bandwidth/netcode#119]
Hi,

I think that it would be better if the `client index` is embedded in both `connection payload packet` and `connection disconnect packet`.

Currently, after receiving a packet, server will iterate overall the array of clients to find the associated `client index` by function `netcode_server_find_client_index_by_address`.

I suggest this way:
- Embed the `client index` in `connection payload packet` and `connection disconnect packet` before sending.
- Retrieve the `client index` from packet after receiving.
- Check if the client at that index is connected and,
- The address stored in `client address array` equals with received packet address

It could be like this:

_connection payload packet_:
```
[client index] (uint32)
[payload data] (1 to 1200 bytes)
```

_connection disconnect packet_:
```
[client index] (uint32)
```

Thanks for considering

**Comment by kienhg96** [comment]
OK, I'll try my best

**Comment by gafferongames** [comment]
I've thought about this more, the cost and complexity of an additional index (on top of the 64 bit client id) is too high a price to pay, for something which could be implemented via a hash table look up on client id instead.

We both want constant time lookups, the BEST way to do this, would be to instead look up the index in a hash table by client id, instead of sending the client index in the packet.

This has the benefit that implementing it this way will also not require any changes in the protocol version.

So if you would like to add this feature, please implement a hash table lookup from client id -> client index, instead of including the client index in packets.

Thanks!

**Comment by kienhg96** [comment]
Agree, and I relized that, the `client index` could not be placed inside the encrypted portion of packet.

**Comment by gafferongames** [comment]
Yes this is another good point.

**Comment by gafferongames** [comment]
Please change 

#define NETCODE_ADDRESS_MAP_BUCKETS 256

To be some function of the max clients, because as the max clients increases for the server, you will need more buckets.
